import json

import requests
from bs4 import BeautifulSoup, NavigableString, Tag


def patch_finder(patch_notes_new):
    url_id = patch_notes_new[0].split()[1].replace('.', '-')
    url = "https://www.leagueoflegends.com/en-gb/news/game-updates/patch-" + url_id + "-notes/"
    return url


def check_if_new_patch():
    # Read saved file for comparison
    patch_notes_old = []
    with open("./already_crawled.txt", "r") as file:
        for line in file:
            text = line.replace('\n', '')
            patch_notes_old.append(text)

    # Crawls and writes recent patchnotes.
    url = "https://www.leagueoflegends.com/en-gb/news/tags/patch-notes/"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, "lxml")

    patch_notes_new = []
    f = open("already_crawled.txt", "w")
    for quote in soup.find_all('h2'):
        f.writelines(quote.text + "\n")
        patch_notes_new.append(quote.text)
    f.close()

    # Checks if the recent patch_notes are newer than the saved ones.
    if patch_notes_old[0] == patch_notes_new[1]:
        print("We have a new Patch!")
        return patch_finder(patch_notes_new)
    else:
        print("Sadly no new patch")
        # input("Press enter and exit")
        # TODO: REMOVE LATER FOR TESTING ONLY
        return patch_finder(patch_notes_new)


url = check_if_new_patch()

response = requests.get(url)
soup = BeautifulSoup(response.content, "lxml")

# Find the start header
start_header = soup.find('h2', string="Big Gameplay Changes")

# Collect content between headers
content = []
collect = 0
if start_header:
    for element in start_header.next_elements:
        if isinstance(element, Tag):  # Check if the element is a tag
            if element.name == "h2":  # Found another h2 tag
                if collect == 2:  # If we've been collecting, stop as we hit another h2
                    break
                collect += 1  # Start collecting after hitting the first h2
                content.append("THIS_IS_FOR_SPLITTING")
            if collect:
                content.append(element.prettify())

# Split at the marker
html_items = []
html_champions = []
current_section = []
section_counter = 0

for item in content:
    if item == "THIS_IS_FOR_SPLITTING":
        if current_section:
            if section_counter == 0:
                html_items = current_section
            else:
                html_champions.append(current_section)
            current_section = []
            section_counter += 1
    else:
        current_section.append(item)

# Check for any remaining content after the last marker
if current_section:
    if section_counter == 0:
        html_items = current_section
    else:
        html_champions.append(current_section)

# Save the content to a JSON file
with open('extracted_content.json', 'w', encoding='utf-8') as file:
    json.dump({
        'html_items': html_items,
        'html_champions': html_champions
    }, file, indent=4)



# Sample HTML snippet provided
html_content = """
"<h2 id=\"patch-champions\">\n Champions\n</h2>\n",
            "<div class=\"content-border\">\n <div class=\"patch-change-block white-stone accent-before\">\n  <div>\n   <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/akshan/\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Akshan.png\"/>\n   </a>\n   <h3 class=\"change-title\" id=\"patch-akshan\">\n    <a href=\"https://www.leagueoflegends.com/en-us/champions/akshan/\">\n     Akshan\n    </a>\n   </h3>\n   <p class=\"summary\">\n    Q movement speed on champion hit no longer scales with level, damage to non-champions decreased. R minimum damage per shot increased, maximum damage adjusted.\n   </p>\n   <blockquote class=\"blockquote context\">\n    Akshan has long had two problems: First, he\u2019s been a fairly frustrating top and mid laner to face, staying just out of reach from his melee opposition while also having incredible roam power. Second, his baseline reliability is quite low, making him incredibly hard to approach in lower-skilled play. We expect Akshan to require a lot of practice to get the most out of him, but we think we can still bring up his baseline. Due to how fair his R is (minions and turrets can block shots, in addition to champions), we think this ability could use some strong buffs that won't compromise the ability\u2019s counter-play. These R buffs should result in up to 50% more ultimate damage in the most extreme cases late-game, but will typically be closer to 10% against low-health opponents.\n   </blockquote>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanQ.png\"/>\n    Q - Avengerang\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      Move Speed on Champion Hit\n     </strong>\n     : 20/25/30/35/40% (+5% per 100 AP) \u21d2\n     <strong>\n      20% at all ranks\n     </strong>\n     (+5% per 100 AP)\n    </li>\n    <li>\n     <strong>\n      Damage to Non-Champions\n     </strong>\n     : 40/52.5/65/77.5/90% \u21d2 40/\n     <strong>\n      50/60/70/80%\n     </strong>\n    </li>\n   </ul>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanR.png\"/>\n    R - Comeuppance\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      Minimum Damage per Bullet\n     </strong>\n     : 20/25/30 (+10% total AD) \u21d2\n     <strong>\n      25/35/45 (+15% total AD)\n     </strong>\n    </li>\n    <li>\n     <strong>\n      Maximum Damage per Bullet\n     </strong>\n     : 80/100/120 (+40% AD) \u21d2\n     <strong>\n      75/105/135 (+45% total AD)\n     </strong>\n    </li>\n   </ul>\n  </div>\n </div>\n</div>\n",
            "<div class=\"patch-change-block white-stone accent-before\">\n <div>\n  <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/akshan/\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Akshan.png\"/>\n  </a>\n  <h3 class=\"change-title\" id=\"patch-akshan\">\n   <a href=\"https://www.leagueoflegends.com/en-us/champions/akshan/\">\n    Akshan\n   </a>\n  </h3>\n  <p class=\"summary\">\n   Q movement speed on champion hit no longer scales with level, damage to non-champions decreased. R minimum damage per shot increased, maximum damage adjusted.\n  </p>\n  <blockquote class=\"blockquote context\">\n   Akshan has long had two problems: First, he\u2019s been a fairly frustrating top and mid laner to face, staying just out of reach from his melee opposition while also having incredible roam power. Second, his baseline reliability is quite low, making him incredibly hard to approach in lower-skilled play. We expect Akshan to require a lot of practice to get the most out of him, but we think we can still bring up his baseline. Due to how fair his R is (minions and turrets can block shots, in addition to champions), we think this ability could use some strong buffs that won't compromise the ability\u2019s counter-play. These R buffs should result in up to 50% more ultimate damage in the most extreme cases late-game, but will typically be closer to 10% against low-health opponents.\n  </blockquote>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanQ.png\"/>\n   Q - Avengerang\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     Move Speed on Champion Hit\n    </strong>\n    : 20/25/30/35/40% (+5% per 100 AP) \u21d2\n    <strong>\n     20% at all ranks\n    </strong>\n    (+5% per 100 AP)\n   </li>\n   <li>\n    <strong>\n     Damage to Non-Champions\n    </strong>\n    : 40/52.5/65/77.5/90% \u21d2 40/\n    <strong>\n     50/60/70/80%\n    </strong>\n   </li>\n  </ul>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanR.png\"/>\n   R - Comeuppance\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     Minimum Damage per Bullet\n    </strong>\n    : 20/25/30 (+10% total AD) \u21d2\n    <strong>\n     25/35/45 (+15% total AD)\n    </strong>\n   </li>\n   <li>\n    <strong>\n     Maximum Damage per Bullet\n    </strong>\n    : 80/100/120 (+40% AD) \u21d2\n    <strong>\n     75/105/135 (+45% total AD)\n    </strong>\n   </li>\n  </ul>\n </div>\n</div>\n",
            "<div>\n <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/akshan/\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Akshan.png\"/>\n </a>\n <h3 class=\"change-title\" id=\"patch-akshan\">\n  <a href=\"https://www.leagueoflegends.com/en-us/champions/akshan/\">\n   Akshan\n  </a>\n </h3>\n <p class=\"summary\">\n  Q movement speed on champion hit no longer scales with level, damage to non-champions decreased. R minimum damage per shot increased, maximum damage adjusted.\n </p>\n <blockquote class=\"blockquote context\">\n  Akshan has long had two problems: First, he\u2019s been a fairly frustrating top and mid laner to face, staying just out of reach from his melee opposition while also having incredible roam power. Second, his baseline reliability is quite low, making him incredibly hard to approach in lower-skilled play. We expect Akshan to require a lot of practice to get the most out of him, but we think we can still bring up his baseline. Due to how fair his R is (minions and turrets can block shots, in addition to champions), we think this ability could use some strong buffs that won't compromise the ability\u2019s counter-play. These R buffs should result in up to 50% more ultimate damage in the most extreme cases late-game, but will typically be closer to 10% against low-health opponents.\n </blockquote>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanQ.png\"/>\n  Q - Avengerang\n </h4>\n <ul>\n  <li>\n   <strong>\n    Move Speed on Champion Hit\n   </strong>\n   : 20/25/30/35/40% (+5% per 100 AP) \u21d2\n   <strong>\n    20% at all ranks\n   </strong>\n   (+5% per 100 AP)\n  </li>\n  <li>\n   <strong>\n    Damage to Non-Champions\n   </strong>\n   : 40/52.5/65/77.5/90% \u21d2 40/\n   <strong>\n    50/60/70/80%\n   </strong>\n  </li>\n </ul>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanR.png\"/>\n  R - Comeuppance\n </h4>\n <ul>\n  <li>\n   <strong>\n    Minimum Damage per Bullet\n   </strong>\n   : 20/25/30 (+10% total AD) \u21d2\n   <strong>\n    25/35/45 (+15% total AD)\n   </strong>\n  </li>\n  <li>\n   <strong>\n    Maximum Damage per Bullet\n   </strong>\n   : 80/100/120 (+40% AD) \u21d2\n   <strong>\n    75/105/135 (+45% total AD)\n   </strong>\n  </li>\n </ul>\n</div>\n",
            "<a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/akshan/\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Akshan.png\"/>\n</a>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Akshan.png\"/>\n",
            "<h3 class=\"change-title\" id=\"patch-akshan\">\n <a href=\"https://www.leagueoflegends.com/en-us/champions/akshan/\">\n  Akshan\n </a>\n</h3>\n",
            "<a href=\"https://www.leagueoflegends.com/en-us/champions/akshan/\">\n Akshan\n</a>\n",
            "<p class=\"summary\">\n Q movement speed on champion hit no longer scales with level, damage to non-champions decreased. R minimum damage per shot increased, maximum damage adjusted.\n</p>\n",
            "<blockquote class=\"blockquote context\">\n Akshan has long had two problems: First, he\u2019s been a fairly frustrating top and mid laner to face, staying just out of reach from his melee opposition while also having incredible roam power. Second, his baseline reliability is quite low, making him incredibly hard to approach in lower-skilled play. We expect Akshan to require a lot of practice to get the most out of him, but we think we can still bring up his baseline. Due to how fair his R is (minions and turrets can block shots, in addition to champions), we think this ability could use some strong buffs that won't compromise the ability\u2019s counter-play. These R buffs should result in up to 50% more ultimate damage in the most extreme cases late-game, but will typically be closer to 10% against low-health opponents.\n</blockquote>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanQ.png\"/>\n Q - Avengerang\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanQ.png\"/>\n",
            "<ul>\n <li>\n  <strong>\n   Move Speed on Champion Hit\n  </strong>\n  : 20/25/30/35/40% (+5% per 100 AP) \u21d2\n  <strong>\n   20% at all ranks\n  </strong>\n  (+5% per 100 AP)\n </li>\n <li>\n  <strong>\n   Damage to Non-Champions\n  </strong>\n  : 40/52.5/65/77.5/90% \u21d2 40/\n  <strong>\n   50/60/70/80%\n  </strong>\n </li>\n</ul>\n",
            "<li>\n <strong>\n  Move Speed on Champion Hit\n </strong>\n : 20/25/30/35/40% (+5% per 100 AP) \u21d2\n <strong>\n  20% at all ranks\n </strong>\n (+5% per 100 AP)\n</li>\n",
            "<strong>\n Move Speed on Champion Hit\n</strong>\n",
            "<strong>\n 20% at all ranks\n</strong>\n",
            "<li>\n <strong>\n  Damage to Non-Champions\n </strong>\n : 40/52.5/65/77.5/90% \u21d2 40/\n <strong>\n  50/60/70/80%\n </strong>\n</li>\n",
            "<strong>\n Damage to Non-Champions\n</strong>\n",
            "<strong>\n 50/60/70/80%\n</strong>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanR.png\"/>\n R - Comeuppance\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/AkshanR.png\"/>\n",
            "<ul>\n <li>\n  <strong>\n   Minimum Damage per Bullet\n  </strong>\n  : 20/25/30 (+10% total AD) \u21d2\n  <strong>\n   25/35/45 (+15% total AD)\n  </strong>\n </li>\n <li>\n  <strong>\n   Maximum Damage per Bullet\n  </strong>\n  : 80/100/120 (+40% AD) \u21d2\n  <strong>\n   75/105/135 (+45% total AD)\n  </strong>\n </li>\n</ul>\n",
            "<li>\n <strong>\n  Minimum Damage per Bullet\n </strong>\n : 20/25/30 (+10% total AD) \u21d2\n <strong>\n  25/35/45 (+15% total AD)\n </strong>\n</li>\n",
            "<strong>\n Minimum Damage per Bullet\n</strong>\n",
            "<strong>\n 25/35/45 (+15% total AD)\n</strong>\n",
            "<li>\n <strong>\n  Maximum Damage per Bullet\n </strong>\n : 80/100/120 (+40% AD) \u21d2\n <strong>\n  75/105/135 (+45% total AD)\n </strong>\n</li>\n",
            "<strong>\n Maximum Damage per Bullet\n</strong>\n",
            "<strong>\n 75/105/135 (+45% total AD)\n</strong>\n",
            "<div class=\"content-border\">\n <div class=\"patch-change-block white-stone accent-before\">\n  <div>\n   <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/bel-veth/\" target=\"_blank\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Belveth.png\"/>\n   </a>\n   <h3 class=\"change-title\" id=\"patch-bel-veth\">\n    <a href=\"https://www.leagueoflegends.com/en-us/champions/bel-veth/\" target=\"_blank\">\n     Bel\u2019Veth\n    </a>\n   </h3>\n   <p class=\"summary\">\n    Passive bonus attack speed adjusted, Q damage decreased, Q damage to monsters increased early game.\n   </p>\n   <blockquote class=\"blockquote context\">\n    Bel\u2019Veth has continued to terrorize the jungle in higher levels of play, so we\u2019re taking a decent-sized swing at her PVP combat power in this patch. As compensation for lower-skilled play, we\u2019re making her jungle a little more forgiving by buffing her early game monster damage. This monster damage buff then becomes a nerf at about 65 bonus AD while her PVP damage is always lower which should result in the high skill skewed nerf that the Void Empress needs.\n   </blockquote>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Belveth_Passive.png\"/>\n    Passive - Death in Lavender\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      Bonus Attack Speed per Stack\n     </strong>\n     : 0.28%-1% (levels 1-13) \u21d2 0.28%-1%\n     <strong>\n      (levels 1-17)\n     </strong>\n     <em>\n      (Note: This means that at levels 2-16, Bel\u2019Veth will have slightly less attack speed, this is most pronounced at level 13.)\n     </em>\n    </li>\n   </ul>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt15dbcb91ec90e0f8/6449e0bf25dc1411155ffd70/050223_BelVeth_Void_Surge.png\"/>\n    Q - Void Surge\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      Damage\n     </strong>\n     : 10/15/20/25/30 (+110% total AD) \u21d2 10/15/20/25/30\n     <strong>\n      (+100% Total AD)\n     </strong>\n    </li>\n    <li>\n     <strong>\n      Monster Damage Modifier\n     </strong>\n     : 140% total damage \u21d2 +45/55/65/75/85 flat damage\n     <em>\n      (Note: This is a buff until 136 total attack damage.)\n     </em>\n    </li>\n   </ul>\n  </div>\n </div>\n</div>\n",
            "<div class=\"patch-change-block white-stone accent-before\">\n <div>\n  <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/bel-veth/\" target=\"_blank\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Belveth.png\"/>\n  </a>\n  <h3 class=\"change-title\" id=\"patch-bel-veth\">\n   <a href=\"https://www.leagueoflegends.com/en-us/champions/bel-veth/\" target=\"_blank\">\n    Bel\u2019Veth\n   </a>\n  </h3>\n  <p class=\"summary\">\n   Passive bonus attack speed adjusted, Q damage decreased, Q damage to monsters increased early game.\n  </p>\n  <blockquote class=\"blockquote context\">\n   Bel\u2019Veth has continued to terrorize the jungle in higher levels of play, so we\u2019re taking a decent-sized swing at her PVP combat power in this patch. As compensation for lower-skilled play, we\u2019re making her jungle a little more forgiving by buffing her early game monster damage. This monster damage buff then becomes a nerf at about 65 bonus AD while her PVP damage is always lower which should result in the high skill skewed nerf that the Void Empress needs.\n  </blockquote>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Belveth_Passive.png\"/>\n   Passive - Death in Lavender\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     Bonus Attack Speed per Stack\n    </strong>\n    : 0.28%-1% (levels 1-13) \u21d2 0.28%-1%\n    <strong>\n     (levels 1-17)\n    </strong>\n    <em>\n     (Note: This means that at levels 2-16, Bel\u2019Veth will have slightly less attack speed, this is most pronounced at level 13.)\n    </em>\n   </li>\n  </ul>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt15dbcb91ec90e0f8/6449e0bf25dc1411155ffd70/050223_BelVeth_Void_Surge.png\"/>\n   Q - Void Surge\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     Damage\n    </strong>\n    : 10/15/20/25/30 (+110% total AD) \u21d2 10/15/20/25/30\n    <strong>\n     (+100% Total AD)\n    </strong>\n   </li>\n   <li>\n    <strong>\n     Monster Damage Modifier\n    </strong>\n    : 140% total damage \u21d2 +45/55/65/75/85 flat damage\n    <em>\n     (Note: This is a buff until 136 total attack damage.)\n    </em>\n   </li>\n  </ul>\n </div>\n</div>\n",
            "<div>\n <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/bel-veth/\" target=\"_blank\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Belveth.png\"/>\n </a>\n <h3 class=\"change-title\" id=\"patch-bel-veth\">\n  <a href=\"https://www.leagueoflegends.com/en-us/champions/bel-veth/\" target=\"_blank\">\n   Bel\u2019Veth\n  </a>\n </h3>\n <p class=\"summary\">\n  Passive bonus attack speed adjusted, Q damage decreased, Q damage to monsters increased early game.\n </p>\n <blockquote class=\"blockquote context\">\n  Bel\u2019Veth has continued to terrorize the jungle in higher levels of play, so we\u2019re taking a decent-sized swing at her PVP combat power in this patch. As compensation for lower-skilled play, we\u2019re making her jungle a little more forgiving by buffing her early game monster damage. This monster damage buff then becomes a nerf at about 65 bonus AD while her PVP damage is always lower which should result in the high skill skewed nerf that the Void Empress needs.\n </blockquote>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Belveth_Passive.png\"/>\n  Passive - Death in Lavender\n </h4>\n <ul>\n  <li>\n   <strong>\n    Bonus Attack Speed per Stack\n   </strong>\n   : 0.28%-1% (levels 1-13) \u21d2 0.28%-1%\n   <strong>\n    (levels 1-17)\n   </strong>\n   <em>\n    (Note: This means that at levels 2-16, Bel\u2019Veth will have slightly less attack speed, this is most pronounced at level 13.)\n   </em>\n  </li>\n </ul>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt15dbcb91ec90e0f8/6449e0bf25dc1411155ffd70/050223_BelVeth_Void_Surge.png\"/>\n  Q - Void Surge\n </h4>\n <ul>\n  <li>\n   <strong>\n    Damage\n   </strong>\n   : 10/15/20/25/30 (+110% total AD) \u21d2 10/15/20/25/30\n   <strong>\n    (+100% Total AD)\n   </strong>\n  </li>\n  <li>\n   <strong>\n    Monster Damage Modifier\n   </strong>\n   : 140% total damage \u21d2 +45/55/65/75/85 flat damage\n   <em>\n    (Note: This is a buff until 136 total attack damage.)\n   </em>\n  </li>\n </ul>\n</div>\n",
            "<a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/bel-veth/\" target=\"_blank\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Belveth.png\"/>\n</a>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Belveth.png\"/>\n",
            "<h3 class=\"change-title\" id=\"patch-bel-veth\">\n <a href=\"https://www.leagueoflegends.com/en-us/champions/bel-veth/\" target=\"_blank\">\n  Bel\u2019Veth\n </a>\n</h3>\n",
            "<a href=\"https://www.leagueoflegends.com/en-us/champions/bel-veth/\" target=\"_blank\">\n Bel\u2019Veth\n</a>\n",
            "<p class=\"summary\">\n Passive bonus attack speed adjusted, Q damage decreased, Q damage to monsters increased early game.\n</p>\n",
            "<blockquote class=\"blockquote context\">\n Bel\u2019Veth has continued to terrorize the jungle in higher levels of play, so we\u2019re taking a decent-sized swing at her PVP combat power in this patch. As compensation for lower-skilled play, we\u2019re making her jungle a little more forgiving by buffing her early game monster damage. This monster damage buff then becomes a nerf at about 65 bonus AD while her PVP damage is always lower which should result in the high skill skewed nerf that the Void Empress needs.\n</blockquote>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Belveth_Passive.png\"/>\n Passive - Death in Lavender\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Belveth_Passive.png\"/>\n",
            "<ul>\n <li>\n  <strong>\n   Bonus Attack Speed per Stack\n  </strong>\n  : 0.28%-1% (levels 1-13) \u21d2 0.28%-1%\n  <strong>\n   (levels 1-17)\n  </strong>\n  <em>\n   (Note: This means that at levels 2-16, Bel\u2019Veth will have slightly less attack speed, this is most pronounced at level 13.)\n  </em>\n </li>\n</ul>\n",
            "<li>\n <strong>\n  Bonus Attack Speed per Stack\n </strong>\n : 0.28%-1% (levels 1-13) \u21d2 0.28%-1%\n <strong>\n  (levels 1-17)\n </strong>\n <em>\n  (Note: This means that at levels 2-16, Bel\u2019Veth will have slightly less attack speed, this is most pronounced at level 13.)\n </em>\n</li>\n",
            "<strong>\n Bonus Attack Speed per Stack\n</strong>\n",
            "<strong>\n (levels 1-17)\n</strong>\n",
            "<em>\n (Note: This means that at levels 2-16, Bel\u2019Veth will have slightly less attack speed, this is most pronounced at level 13.)\n</em>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt15dbcb91ec90e0f8/6449e0bf25dc1411155ffd70/050223_BelVeth_Void_Surge.png\"/>\n Q - Void Surge\n</h4>\n",
            "<img src=\"https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt15dbcb91ec90e0f8/6449e0bf25dc1411155ffd70/050223_BelVeth_Void_Surge.png\"/>\n",
            "<ul>\n <li>\n  <strong>\n   Damage\n  </strong>\n  : 10/15/20/25/30 (+110% total AD) \u21d2 10/15/20/25/30\n  <strong>\n   (+100% Total AD)\n  </strong>\n </li>\n <li>\n  <strong>\n   Monster Damage Modifier\n  </strong>\n  : 140% total damage \u21d2 +45/55/65/75/85 flat damage\n  <em>\n   (Note: This is a buff until 136 total attack damage.)\n  </em>\n </li>\n</ul>\n",
            "<li>\n <strong>\n  Damage\n </strong>\n : 10/15/20/25/30 (+110% total AD) \u21d2 10/15/20/25/30\n <strong>\n  (+100% Total AD)\n </strong>\n</li>\n",
            "<strong>\n Damage\n</strong>\n",
            "<strong>\n (+100% Total AD)\n</strong>\n",
            "<li>\n <strong>\n  Monster Damage Modifier\n </strong>\n : 140% total damage \u21d2 +45/55/65/75/85 flat damage\n <em>\n  (Note: This is a buff until 136 total attack damage.)\n </em>\n</li>\n",
            "<strong>\n Monster Damage Modifier\n</strong>\n",
            "<em>\n (Note: This is a buff until 136 total attack damage.)\n</em>\n",
            "<div class=\"content-border\">\n <div class=\"patch-change-block white-stone accent-before\">\n  <div>\n   <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/kennen/\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Kennen.png\"/>\n   </a>\n   <h3 class=\"change-title\" id=\"patch-kennen\">\n    <a href=\"https://www.leagueoflegends.com/en-us/champions/kennen/\">\n     Kennen\n    </a>\n   </h3>\n   <p class=\"summary\">\n    E damage range indicator added. R animation added, can now cast while moving.\n   </p>\n   <blockquote class=\"blockquote context\">\n    Kennen\u2019s a pretty sad yordle in his current state, and that\u2019s Amumu\u2019s job. We\u2019re giving Kennen a meaningful buff by way of making his kit more synergistic with itself. This fast-moving, zapping ninja no longer stands in place when powering up Slicing Maelstrom. We\u2019re turning this anti-synergy with Lightning Rush into a positive one, allowing him to more quickly reach his targets. He\u2019s also got a brand new animation for powering up his R to match the new cast paradigm!\n   </blockquote>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenLightningRush.png\"/>\n    E - Lightning Rush\n   </h4>\n   <ul>\n    <li>\n     <span class=\"new\">\n      new\n     </span>\n     Added a range indicator for the damage radius.\n    </li>\n   </ul>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenShurikenStorm.png\"/>\n    R - Slicing Maelstrom\n   </h4>\n   <ul>\n    <li>\n     <span class=\"new\">\n      new\n     </span>\n     New animation has been added for Slicing Maelstrom.\n    </li>\n    <li>\n     <span class=\"new\">\n      new\n     </span>\n     Kennen can now cast his ultimate while moving.\n    </li>\n   </ul>\n  </div>\n </div>\n</div>\n",
            "<div class=\"patch-change-block white-stone accent-before\">\n <div>\n  <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/kennen/\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Kennen.png\"/>\n  </a>\n  <h3 class=\"change-title\" id=\"patch-kennen\">\n   <a href=\"https://www.leagueoflegends.com/en-us/champions/kennen/\">\n    Kennen\n   </a>\n  </h3>\n  <p class=\"summary\">\n   E damage range indicator added. R animation added, can now cast while moving.\n  </p>\n  <blockquote class=\"blockquote context\">\n   Kennen\u2019s a pretty sad yordle in his current state, and that\u2019s Amumu\u2019s job. We\u2019re giving Kennen a meaningful buff by way of making his kit more synergistic with itself. This fast-moving, zapping ninja no longer stands in place when powering up Slicing Maelstrom. We\u2019re turning this anti-synergy with Lightning Rush into a positive one, allowing him to more quickly reach his targets. He\u2019s also got a brand new animation for powering up his R to match the new cast paradigm!\n  </blockquote>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenLightningRush.png\"/>\n   E - Lightning Rush\n  </h4>\n  <ul>\n   <li>\n    <span class=\"new\">\n     new\n    </span>\n    Added a range indicator for the damage radius.\n   </li>\n  </ul>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenShurikenStorm.png\"/>\n   R - Slicing Maelstrom\n  </h4>\n  <ul>\n   <li>\n    <span class=\"new\">\n     new\n    </span>\n    New animation has been added for Slicing Maelstrom.\n   </li>\n   <li>\n    <span class=\"new\">\n     new\n    </span>\n    Kennen can now cast his ultimate while moving.\n   </li>\n  </ul>\n </div>\n</div>\n",
            "<div>\n <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/kennen/\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Kennen.png\"/>\n </a>\n <h3 class=\"change-title\" id=\"patch-kennen\">\n  <a href=\"https://www.leagueoflegends.com/en-us/champions/kennen/\">\n   Kennen\n  </a>\n </h3>\n <p class=\"summary\">\n  E damage range indicator added. R animation added, can now cast while moving.\n </p>\n <blockquote class=\"blockquote context\">\n  Kennen\u2019s a pretty sad yordle in his current state, and that\u2019s Amumu\u2019s job. We\u2019re giving Kennen a meaningful buff by way of making his kit more synergistic with itself. This fast-moving, zapping ninja no longer stands in place when powering up Slicing Maelstrom. We\u2019re turning this anti-synergy with Lightning Rush into a positive one, allowing him to more quickly reach his targets. He\u2019s also got a brand new animation for powering up his R to match the new cast paradigm!\n </blockquote>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenLightningRush.png\"/>\n  E - Lightning Rush\n </h4>\n <ul>\n  <li>\n   <span class=\"new\">\n    new\n   </span>\n   Added a range indicator for the damage radius.\n  </li>\n </ul>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenShurikenStorm.png\"/>\n  R - Slicing Maelstrom\n </h4>\n <ul>\n  <li>\n   <span class=\"new\">\n    new\n   </span>\n   New animation has been added for Slicing Maelstrom.\n  </li>\n  <li>\n   <span class=\"new\">\n    new\n   </span>\n   Kennen can now cast his ultimate while moving.\n  </li>\n </ul>\n</div>\n",
            "<a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/kennen/\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Kennen.png\"/>\n</a>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Kennen.png\"/>\n",
            "<h3 class=\"change-title\" id=\"patch-kennen\">\n <a href=\"https://www.leagueoflegends.com/en-us/champions/kennen/\">\n  Kennen\n </a>\n</h3>\n",
            "<a href=\"https://www.leagueoflegends.com/en-us/champions/kennen/\">\n Kennen\n</a>\n",
            "<p class=\"summary\">\n E damage range indicator added. R animation added, can now cast while moving.\n</p>\n",
            "<blockquote class=\"blockquote context\">\n Kennen\u2019s a pretty sad yordle in his current state, and that\u2019s Amumu\u2019s job. We\u2019re giving Kennen a meaningful buff by way of making his kit more synergistic with itself. This fast-moving, zapping ninja no longer stands in place when powering up Slicing Maelstrom. We\u2019re turning this anti-synergy with Lightning Rush into a positive one, allowing him to more quickly reach his targets. He\u2019s also got a brand new animation for powering up his R to match the new cast paradigm!\n</blockquote>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenLightningRush.png\"/>\n E - Lightning Rush\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenLightningRush.png\"/>\n",
            "<ul>\n <li>\n  <span class=\"new\">\n   new\n  </span>\n  Added a range indicator for the damage radius.\n </li>\n</ul>\n",
            "<li>\n <span class=\"new\">\n  new\n </span>\n Added a range indicator for the damage radius.\n</li>\n",
            "<span class=\"new\">\n new\n</span>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenShurikenStorm.png\"/>\n R - Slicing Maelstrom\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/KennenShurikenStorm.png\"/>\n",
            "<ul>\n <li>\n  <span class=\"new\">\n   new\n  </span>\n  New animation has been added for Slicing Maelstrom.\n </li>\n <li>\n  <span class=\"new\">\n   new\n  </span>\n  Kennen can now cast his ultimate while moving.\n </li>\n</ul>\n",
            "<li>\n <span class=\"new\">\n  new\n </span>\n New animation has been added for Slicing Maelstrom.\n</li>\n",
            "<span class=\"new\">\n new\n</span>\n",
            "<li>\n <span class=\"new\">\n  new\n </span>\n Kennen can now cast his ultimate while moving.\n</li>\n",
            "<span class=\"new\">\n new\n</span>\n",
            "<div class=\"content-border\">\n <div class=\"patch-change-block white-stone accent-before\">\n  <div>\n   <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/nilah/\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Nilah.png\"/>\n   </a>\n   <h3 class=\"change-title\" id=\"patch-kennen\">\n    <a href=\"https://www.leagueoflegends.com/en-us/champions/nilah/\">\n     Nilah\n    </a>\n   </h3>\n   <p class=\"summary\">\n    Q minimum damage decreased, bonus attack speed increased, bonus damage based on critical strike chance decreased.\n   </p>\n   <blockquote class=\"blockquote context\">\n    Back in 13.22, we nerfed Nilah\u2019s attack speed from Q, which ended up nerfing her more in high level play. We\u2019re reverting that nerf and nudging her gameplay toward consistent DPS as opposed to burst damage, so we\u2019re returning that attack speed and instead reducing some up-front burst damage on her active instead. Nilah is a bit stronger than where we think she should be, so our intent for these changes to leave Nilah a bit weaker than she currently is, especially in lower-skilled play.\n   </blockquote>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/NilahQ.png\"/>\n    Q - Formless Blade\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      Minimum Damage\n     </strong>\n     : 5/10/15/20/25 (+90/97.5/105/112.5/120% total AD) \u21d2 5/10/15/20/25\n     <strong>\n      (+90/95/100/105/110% total AD)\n     </strong>\n    </li>\n    <li>\n     <strong>\n      Bonus Attack Speed\n     </strong>\n     : 10-50% (based on level) \u21d2 10-\n     <strong>\n      60%\n     </strong>\n     (based on level)\n    </li>\n    <li>\n     <strong>\n      Critical Strike Chance Damage Modifier\n     </strong>\n     : 100-220% (based on critical strike chance) \u21d2 100-200% (based on critical strike chance)\n    </li>\n   </ul>\n  </div>\n </div>\n</div>\n",
            "<div class=\"patch-change-block white-stone accent-before\">\n <div>\n  <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/nilah/\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Nilah.png\"/>\n  </a>\n  <h3 class=\"change-title\" id=\"patch-kennen\">\n   <a href=\"https://www.leagueoflegends.com/en-us/champions/nilah/\">\n    Nilah\n   </a>\n  </h3>\n  <p class=\"summary\">\n   Q minimum damage decreased, bonus attack speed increased, bonus damage based on critical strike chance decreased.\n  </p>\n  <blockquote class=\"blockquote context\">\n   Back in 13.22, we nerfed Nilah\u2019s attack speed from Q, which ended up nerfing her more in high level play. We\u2019re reverting that nerf and nudging her gameplay toward consistent DPS as opposed to burst damage, so we\u2019re returning that attack speed and instead reducing some up-front burst damage on her active instead. Nilah is a bit stronger than where we think she should be, so our intent for these changes to leave Nilah a bit weaker than she currently is, especially in lower-skilled play.\n  </blockquote>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/NilahQ.png\"/>\n   Q - Formless Blade\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     Minimum Damage\n    </strong>\n    : 5/10/15/20/25 (+90/97.5/105/112.5/120% total AD) \u21d2 5/10/15/20/25\n    <strong>\n     (+90/95/100/105/110% total AD)\n    </strong>\n   </li>\n   <li>\n    <strong>\n     Bonus Attack Speed\n    </strong>\n    : 10-50% (based on level) \u21d2 10-\n    <strong>\n     60%\n    </strong>\n    (based on level)\n   </li>\n   <li>\n    <strong>\n     Critical Strike Chance Damage Modifier\n    </strong>\n    : 100-220% (based on critical strike chance) \u21d2 100-200% (based on critical strike chance)\n   </li>\n  </ul>\n </div>\n</div>\n",
            "<div>\n <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/nilah/\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Nilah.png\"/>\n </a>\n <h3 class=\"change-title\" id=\"patch-kennen\">\n  <a href=\"https://www.leagueoflegends.com/en-us/champions/nilah/\">\n   Nilah\n  </a>\n </h3>\n <p class=\"summary\">\n  Q minimum damage decreased, bonus attack speed increased, bonus damage based on critical strike chance decreased.\n </p>\n <blockquote class=\"blockquote context\">\n  Back in 13.22, we nerfed Nilah\u2019s attack speed from Q, which ended up nerfing her more in high level play. We\u2019re reverting that nerf and nudging her gameplay toward consistent DPS as opposed to burst damage, so we\u2019re returning that attack speed and instead reducing some up-front burst damage on her active instead. Nilah is a bit stronger than where we think she should be, so our intent for these changes to leave Nilah a bit weaker than she currently is, especially in lower-skilled play.\n </blockquote>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/NilahQ.png\"/>\n  Q - Formless Blade\n </h4>\n <ul>\n  <li>\n   <strong>\n    Minimum Damage\n   </strong>\n   : 5/10/15/20/25 (+90/97.5/105/112.5/120% total AD) \u21d2 5/10/15/20/25\n   <strong>\n    (+90/95/100/105/110% total AD)\n   </strong>\n  </li>\n  <li>\n   <strong>\n    Bonus Attack Speed\n   </strong>\n   : 10-50% (based on level) \u21d2 10-\n   <strong>\n    60%\n   </strong>\n   (based on level)\n  </li>\n  <li>\n   <strong>\n    Critical Strike Chance Damage Modifier\n   </strong>\n   : 100-220% (based on critical strike chance) \u21d2 100-200% (based on critical strike chance)\n  </li>\n </ul>\n</div>\n",
            "<a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/nilah/\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Nilah.png\"/>\n</a>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Nilah.png\"/>\n",
            "<h3 class=\"change-title\" id=\"patch-kennen\">\n <a href=\"https://www.leagueoflegends.com/en-us/champions/nilah/\">\n  Nilah\n </a>\n</h3>\n",
            "<a href=\"https://www.leagueoflegends.com/en-us/champions/nilah/\">\n Nilah\n</a>\n",
            "<p class=\"summary\">\n Q minimum damage decreased, bonus attack speed increased, bonus damage based on critical strike chance decreased.\n</p>\n",
            "<blockquote class=\"blockquote context\">\n Back in 13.22, we nerfed Nilah\u2019s attack speed from Q, which ended up nerfing her more in high level play. We\u2019re reverting that nerf and nudging her gameplay toward consistent DPS as opposed to burst damage, so we\u2019re returning that attack speed and instead reducing some up-front burst damage on her active instead. Nilah is a bit stronger than where we think she should be, so our intent for these changes to leave Nilah a bit weaker than she currently is, especially in lower-skilled play.\n</blockquote>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/NilahQ.png\"/>\n Q - Formless Blade\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/NilahQ.png\"/>\n",
            "<ul>\n <li>\n  <strong>\n   Minimum Damage\n  </strong>\n  : 5/10/15/20/25 (+90/97.5/105/112.5/120% total AD) \u21d2 5/10/15/20/25\n  <strong>\n   (+90/95/100/105/110% total AD)\n  </strong>\n </li>\n <li>\n  <strong>\n   Bonus Attack Speed\n  </strong>\n  : 10-50% (based on level) \u21d2 10-\n  <strong>\n   60%\n  </strong>\n  (based on level)\n </li>\n <li>\n  <strong>\n   Critical Strike Chance Damage Modifier\n  </strong>\n  : 100-220% (based on critical strike chance) \u21d2 100-200% (based on critical strike chance)\n </li>\n</ul>\n",
            "<li>\n <strong>\n  Minimum Damage\n </strong>\n : 5/10/15/20/25 (+90/97.5/105/112.5/120% total AD) \u21d2 5/10/15/20/25\n <strong>\n  (+90/95/100/105/110% total AD)\n </strong>\n</li>\n",
            "<strong>\n Minimum Damage\n</strong>\n",
            "<strong>\n (+90/95/100/105/110% total AD)\n</strong>\n",
            "<li>\n <strong>\n  Bonus Attack Speed\n </strong>\n : 10-50% (based on level) \u21d2 10-\n <strong>\n  60%\n </strong>\n (based on level)\n</li>\n",
            "<strong>\n Bonus Attack Speed\n</strong>\n",
            "<strong>\n 60%\n</strong>\n",
            "<li>\n <strong>\n  Critical Strike Chance Damage Modifier\n </strong>\n : 100-220% (based on critical strike chance) \u21d2 100-200% (based on critical strike chance)\n</li>\n",
            "<strong>\n Critical Strike Chance Damage Modifier\n</strong>\n",
            "<div class=\"content-border\">\n <div class=\"patch-change-block white-stone accent-before\">\n  <div>\n   <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/sejuani/\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Sejuani.png\"/>\n   </a>\n   <h3 class=\"change-title\" id=\"patch-sejuani\">\n    <a href=\"https://www.leagueoflegends.com/en-us/champions/sejuani/\">\n     Sejuani\n    </a>\n   </h3>\n   <p class=\"summary\">\n    Passive bonus resistances increased. W damage adjusted.\n   </p>\n   <blockquote class=\"blockquote context\">\n    Sejuani\u2019s had the unfortunate fate of being left weaker than she ought to in order to not make the pro play jungle pool too\n    <em>\n     boaring\n    </em>\n    . Now that we won\u2019t see Pro play for a few patches, we\u2019re rushing to her aid. We\u2019re trying to give her a mix of added damage and durability that strongly scales with her gold income, as pro junglers tend to get much less gold than the rest of us.\n   </blockquote>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Sejuani_passive.png\"/>\n    Passive - Fury of the North, Frost Armor\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      Bonus Resistances\n     </strong>\n     : 10 (+50% Bonus Armor/Magic Resistance) \u21d2 10 (\n     <strong>\n      +75%\n     </strong>\n     Bonus Armor/Magic Resistance)\n    </li>\n   </ul>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SejuaniW.png\"/>\n    W - Winter\u2019s Wrath\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      First Hit Damage\n     </strong>\n     : 10/15/20/25/30 (+20% AP) (+2% of her maximum health) \u21d2\n     <strong>\n      5/15/25/35/45\n     </strong>\n     (+20% AP)\n     <strong>\n      (+4% of her maximum health)\n     </strong>\n    </li>\n    <li>\n     <strong>\n      Second Hit Damage\n     </strong>\n     : 20/60/100/140/180 (+60% AP) (+6% of her maximum health) \u21d2\n     <strong>\n      5/25/45/65/85\n     </strong>\n     (+60% AP)\n     <strong>\n      (+8% of her maximum health)\n     </strong>\n    </li>\n    <li>\n     <strong>\n      Maximum Damage\n     </strong>\n     : 30/75/120/165/210 (+80% AP) (+8% of her maximum health) \u21d2\n     <strong>\n      10/40/70/100/130\n     </strong>\n     (+80% AP)\n     <strong>\n      (+12% of her maximum health)\n     </strong>\n    </li>\n   </ul>\n  </div>\n </div>\n</div>\n",
            "<div class=\"patch-change-block white-stone accent-before\">\n <div>\n  <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/sejuani/\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Sejuani.png\"/>\n  </a>\n  <h3 class=\"change-title\" id=\"patch-sejuani\">\n   <a href=\"https://www.leagueoflegends.com/en-us/champions/sejuani/\">\n    Sejuani\n   </a>\n  </h3>\n  <p class=\"summary\">\n   Passive bonus resistances increased. W damage adjusted.\n  </p>\n  <blockquote class=\"blockquote context\">\n   Sejuani\u2019s had the unfortunate fate of being left weaker than she ought to in order to not make the pro play jungle pool too\n   <em>\n    boaring\n   </em>\n   . Now that we won\u2019t see Pro play for a few patches, we\u2019re rushing to her aid. We\u2019re trying to give her a mix of added damage and durability that strongly scales with her gold income, as pro junglers tend to get much less gold than the rest of us.\n  </blockquote>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Sejuani_passive.png\"/>\n   Passive - Fury of the North, Frost Armor\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     Bonus Resistances\n    </strong>\n    : 10 (+50% Bonus Armor/Magic Resistance) \u21d2 10 (\n    <strong>\n     +75%\n    </strong>\n    Bonus Armor/Magic Resistance)\n   </li>\n  </ul>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SejuaniW.png\"/>\n   W - Winter\u2019s Wrath\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     First Hit Damage\n    </strong>\n    : 10/15/20/25/30 (+20% AP) (+2% of her maximum health) \u21d2\n    <strong>\n     5/15/25/35/45\n    </strong>\n    (+20% AP)\n    <strong>\n     (+4% of her maximum health)\n    </strong>\n   </li>\n   <li>\n    <strong>\n     Second Hit Damage\n    </strong>\n    : 20/60/100/140/180 (+60% AP) (+6% of her maximum health) \u21d2\n    <strong>\n     5/25/45/65/85\n    </strong>\n    (+60% AP)\n    <strong>\n     (+8% of her maximum health)\n    </strong>\n   </li>\n   <li>\n    <strong>\n     Maximum Damage\n    </strong>\n    : 30/75/120/165/210 (+80% AP) (+8% of her maximum health) \u21d2\n    <strong>\n     10/40/70/100/130\n    </strong>\n    (+80% AP)\n    <strong>\n     (+12% of her maximum health)\n    </strong>\n   </li>\n  </ul>\n </div>\n</div>\n",
            "<div>\n <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/sejuani/\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Sejuani.png\"/>\n </a>\n <h3 class=\"change-title\" id=\"patch-sejuani\">\n  <a href=\"https://www.leagueoflegends.com/en-us/champions/sejuani/\">\n   Sejuani\n  </a>\n </h3>\n <p class=\"summary\">\n  Passive bonus resistances increased. W damage adjusted.\n </p>\n <blockquote class=\"blockquote context\">\n  Sejuani\u2019s had the unfortunate fate of being left weaker than she ought to in order to not make the pro play jungle pool too\n  <em>\n   boaring\n  </em>\n  . Now that we won\u2019t see Pro play for a few patches, we\u2019re rushing to her aid. We\u2019re trying to give her a mix of added damage and durability that strongly scales with her gold income, as pro junglers tend to get much less gold than the rest of us.\n </blockquote>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Sejuani_passive.png\"/>\n  Passive - Fury of the North, Frost Armor\n </h4>\n <ul>\n  <li>\n   <strong>\n    Bonus Resistances\n   </strong>\n   : 10 (+50% Bonus Armor/Magic Resistance) \u21d2 10 (\n   <strong>\n    +75%\n   </strong>\n   Bonus Armor/Magic Resistance)\n  </li>\n </ul>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SejuaniW.png\"/>\n  W - Winter\u2019s Wrath\n </h4>\n <ul>\n  <li>\n   <strong>\n    First Hit Damage\n   </strong>\n   : 10/15/20/25/30 (+20% AP) (+2% of her maximum health) \u21d2\n   <strong>\n    5/15/25/35/45\n   </strong>\n   (+20% AP)\n   <strong>\n    (+4% of her maximum health)\n   </strong>\n  </li>\n  <li>\n   <strong>\n    Second Hit Damage\n   </strong>\n   : 20/60/100/140/180 (+60% AP) (+6% of her maximum health) \u21d2\n   <strong>\n    5/25/45/65/85\n   </strong>\n   (+60% AP)\n   <strong>\n    (+8% of her maximum health)\n   </strong>\n  </li>\n  <li>\n   <strong>\n    Maximum Damage\n   </strong>\n   : 30/75/120/165/210 (+80% AP) (+8% of her maximum health) \u21d2\n   <strong>\n    10/40/70/100/130\n   </strong>\n   (+80% AP)\n   <strong>\n    (+12% of her maximum health)\n   </strong>\n  </li>\n </ul>\n</div>\n",
            "<a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/sejuani/\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Sejuani.png\"/>\n</a>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Sejuani.png\"/>\n",
            "<h3 class=\"change-title\" id=\"patch-sejuani\">\n <a href=\"https://www.leagueoflegends.com/en-us/champions/sejuani/\">\n  Sejuani\n </a>\n</h3>\n",
            "<a href=\"https://www.leagueoflegends.com/en-us/champions/sejuani/\">\n Sejuani\n</a>\n",
            "<p class=\"summary\">\n Passive bonus resistances increased. W damage adjusted.\n</p>\n",
            "<blockquote class=\"blockquote context\">\n Sejuani\u2019s had the unfortunate fate of being left weaker than she ought to in order to not make the pro play jungle pool too\n <em>\n  boaring\n </em>\n . Now that we won\u2019t see Pro play for a few patches, we\u2019re rushing to her aid. We\u2019re trying to give her a mix of added damage and durability that strongly scales with her gold income, as pro junglers tend to get much less gold than the rest of us.\n</blockquote>\n",
            "<em>\n boaring\n</em>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Sejuani_passive.png\"/>\n Passive - Fury of the North, Frost Armor\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/passive/Sejuani_passive.png\"/>\n",
            "<ul>\n <li>\n  <strong>\n   Bonus Resistances\n  </strong>\n  : 10 (+50% Bonus Armor/Magic Resistance) \u21d2 10 (\n  <strong>\n   +75%\n  </strong>\n  Bonus Armor/Magic Resistance)\n </li>\n</ul>\n",
            "<li>\n <strong>\n  Bonus Resistances\n </strong>\n : 10 (+50% Bonus Armor/Magic Resistance) \u21d2 10 (\n <strong>\n  +75%\n </strong>\n Bonus Armor/Magic Resistance)\n</li>\n",
            "<strong>\n Bonus Resistances\n</strong>\n",
            "<strong>\n +75%\n</strong>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SejuaniW.png\"/>\n W - Winter\u2019s Wrath\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SejuaniW.png\"/>\n",
            "<ul>\n <li>\n  <strong>\n   First Hit Damage\n  </strong>\n  : 10/15/20/25/30 (+20% AP) (+2% of her maximum health) \u21d2\n  <strong>\n   5/15/25/35/45\n  </strong>\n  (+20% AP)\n  <strong>\n   (+4% of her maximum health)\n  </strong>\n </li>\n <li>\n  <strong>\n   Second Hit Damage\n  </strong>\n  : 20/60/100/140/180 (+60% AP) (+6% of her maximum health) \u21d2\n  <strong>\n   5/25/45/65/85\n  </strong>\n  (+60% AP)\n  <strong>\n   (+8% of her maximum health)\n  </strong>\n </li>\n <li>\n  <strong>\n   Maximum Damage\n  </strong>\n  : 30/75/120/165/210 (+80% AP) (+8% of her maximum health) \u21d2\n  <strong>\n   10/40/70/100/130\n  </strong>\n  (+80% AP)\n  <strong>\n   (+12% of her maximum health)\n  </strong>\n </li>\n</ul>\n",
            "<li>\n <strong>\n  First Hit Damage\n </strong>\n : 10/15/20/25/30 (+20% AP) (+2% of her maximum health) \u21d2\n <strong>\n  5/15/25/35/45\n </strong>\n (+20% AP)\n <strong>\n  (+4% of her maximum health)\n </strong>\n</li>\n",
            "<strong>\n First Hit Damage\n</strong>\n",
            "<strong>\n 5/15/25/35/45\n</strong>\n",
            "<strong>\n (+4% of her maximum health)\n</strong>\n",
            "<li>\n <strong>\n  Second Hit Damage\n </strong>\n : 20/60/100/140/180 (+60% AP) (+6% of her maximum health) \u21d2\n <strong>\n  5/25/45/65/85\n </strong>\n (+60% AP)\n <strong>\n  (+8% of her maximum health)\n </strong>\n</li>\n",
            "<strong>\n Second Hit Damage\n</strong>\n",
            "<strong>\n 5/25/45/65/85\n</strong>\n",
            "<strong>\n (+8% of her maximum health)\n</strong>\n",
            "<li>\n <strong>\n  Maximum Damage\n </strong>\n : 30/75/120/165/210 (+80% AP) (+8% of her maximum health) \u21d2\n <strong>\n  10/40/70/100/130\n </strong>\n (+80% AP)\n <strong>\n  (+12% of her maximum health)\n </strong>\n</li>\n",
            "<strong>\n Maximum Damage\n</strong>\n",
            "<strong>\n 10/40/70/100/130\n</strong>\n",
            "<strong>\n (+12% of her maximum health)\n</strong>\n",
            "<div class=\"content-border\">\n <div class=\"patch-change-block white-stone accent-before\">\n  <div>\n   <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/skarner/\">\n    <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Skarner.png\"/>\n   </a>\n   <h3 class=\"change-title\" id=\"patch-skarner\">\n    <a href=\"https://www.leagueoflegends.com/en-us/champions/skarner/\">\n     Skarner\n    </a>\n   </h3>\n   <p class=\"summary\">\n    Mana regen growth increased. Q damage decreased, buff no longer refreshed when hitting wards/plants. W slow decreased.\n   </p>\n   <blockquote class=\"blockquote context\">\n    Skarner is currently very overpowered, especially in elite play, where he\u2019s making the Rift AND enemy\u2019s boots quake. His potent early game often ends games before other champions can reach their power spikes which is why we\u2019re going after his early game. We\u2019ll be doing this by taking down a mix of his early damage and his sticking power with his Q and W. The mana regen line is here to give him a bit of compensation in top lane, as he\u2019s currently a much stronger jungler than top laner and players are clearly happy to play him in both roles.\n   </blockquote>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title\">\n    Base Stats\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      Mana Regeneration Growth\n     </strong>\n     : 0.6 \u21d2 0.75\n    </li>\n   </ul>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerQ.png\"/>\n    Q - Shattered Earth / Upheaval\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      Damage per Hit\n     </strong>\n     : 10/25/40/55/70 (+60% bonus AD) (+5% of his bonus health) \u21d2\n     <strong>\n      10/20/30/40/50\n     </strong>\n     (+60% bonus AD) (+5% of his bonus health)\n    </li>\n    <li>\n     <span class=\"removed\">\n      removed\n     </span>\n     Q no longer refreshes the buff duration upon attacking Wards or Plants.\n    </li>\n   </ul>\n   <hr class=\"divider\"/>\n   <h4 class=\"change-detail-title ability-title\">\n    <img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerW.png\"/>\n    W - Seismic Bastion\n   </h4>\n   <ul>\n    <li>\n     <strong>\n      Slow\n     </strong>\n     : 20/25/30/35/40% \u21d2 20% at all ranks\n    </li>\n    <li>\n     <strong>\n      Shield\n     </strong>\n     : 9% maximum health \u21d2 8% maximum health\n    </li>\n   </ul>\n  </div>\n </div>\n</div>\n",
            "<div class=\"patch-change-block white-stone accent-before\">\n <div>\n  <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/skarner/\">\n   <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Skarner.png\"/>\n  </a>\n  <h3 class=\"change-title\" id=\"patch-skarner\">\n   <a href=\"https://www.leagueoflegends.com/en-us/champions/skarner/\">\n    Skarner\n   </a>\n  </h3>\n  <p class=\"summary\">\n   Mana regen growth increased. Q damage decreased, buff no longer refreshed when hitting wards/plants. W slow decreased.\n  </p>\n  <blockquote class=\"blockquote context\">\n   Skarner is currently very overpowered, especially in elite play, where he\u2019s making the Rift AND enemy\u2019s boots quake. His potent early game often ends games before other champions can reach their power spikes which is why we\u2019re going after his early game. We\u2019ll be doing this by taking down a mix of his early damage and his sticking power with his Q and W. The mana regen line is here to give him a bit of compensation in top lane, as he\u2019s currently a much stronger jungler than top laner and players are clearly happy to play him in both roles.\n  </blockquote>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title\">\n   Base Stats\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     Mana Regeneration Growth\n    </strong>\n    : 0.6 \u21d2 0.75\n   </li>\n  </ul>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerQ.png\"/>\n   Q - Shattered Earth / Upheaval\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     Damage per Hit\n    </strong>\n    : 10/25/40/55/70 (+60% bonus AD) (+5% of his bonus health) \u21d2\n    <strong>\n     10/20/30/40/50\n    </strong>\n    (+60% bonus AD) (+5% of his bonus health)\n   </li>\n   <li>\n    <span class=\"removed\">\n     removed\n    </span>\n    Q no longer refreshes the buff duration upon attacking Wards or Plants.\n   </li>\n  </ul>\n  <hr class=\"divider\"/>\n  <h4 class=\"change-detail-title ability-title\">\n   <img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerW.png\"/>\n   W - Seismic Bastion\n  </h4>\n  <ul>\n   <li>\n    <strong>\n     Slow\n    </strong>\n    : 20/25/30/35/40% \u21d2 20% at all ranks\n   </li>\n   <li>\n    <strong>\n     Shield\n    </strong>\n    : 9% maximum health \u21d2 8% maximum health\n   </li>\n  </ul>\n </div>\n</div>\n",
            "<div>\n <a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/skarner/\">\n  <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Skarner.png\"/>\n </a>\n <h3 class=\"change-title\" id=\"patch-skarner\">\n  <a href=\"https://www.leagueoflegends.com/en-us/champions/skarner/\">\n   Skarner\n  </a>\n </h3>\n <p class=\"summary\">\n  Mana regen growth increased. Q damage decreased, buff no longer refreshed when hitting wards/plants. W slow decreased.\n </p>\n <blockquote class=\"blockquote context\">\n  Skarner is currently very overpowered, especially in elite play, where he\u2019s making the Rift AND enemy\u2019s boots quake. His potent early game often ends games before other champions can reach their power spikes which is why we\u2019re going after his early game. We\u2019ll be doing this by taking down a mix of his early damage and his sticking power with his Q and W. The mana regen line is here to give him a bit of compensation in top lane, as he\u2019s currently a much stronger jungler than top laner and players are clearly happy to play him in both roles.\n </blockquote>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title\">\n  Base Stats\n </h4>\n <ul>\n  <li>\n   <strong>\n    Mana Regeneration Growth\n   </strong>\n   : 0.6 \u21d2 0.75\n  </li>\n </ul>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerQ.png\"/>\n  Q - Shattered Earth / Upheaval\n </h4>\n <ul>\n  <li>\n   <strong>\n    Damage per Hit\n   </strong>\n   : 10/25/40/55/70 (+60% bonus AD) (+5% of his bonus health) \u21d2\n   <strong>\n    10/20/30/40/50\n   </strong>\n   (+60% bonus AD) (+5% of his bonus health)\n  </li>\n  <li>\n   <span class=\"removed\">\n    removed\n   </span>\n   Q no longer refreshes the buff duration upon attacking Wards or Plants.\n  </li>\n </ul>\n <hr class=\"divider\"/>\n <h4 class=\"change-detail-title ability-title\">\n  <img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerW.png\"/>\n  W - Seismic Bastion\n </h4>\n <ul>\n  <li>\n   <strong>\n    Slow\n   </strong>\n   : 20/25/30/35/40% \u21d2 20% at all ranks\n  </li>\n  <li>\n   <strong>\n    Shield\n   </strong>\n   : 9% maximum health \u21d2 8% maximum health\n  </li>\n </ul>\n</div>\n",
            "<a class=\"reference-link\" href=\"https://www.leagueoflegends.com/en-us/champions/skarner/\">\n <img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Skarner.png\"/>\n</a>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=http://ddragon.leagueoflegends.com/cdn/14.8.1/img/champion/Skarner.png\"/>\n",
            "<h3 class=\"change-title\" id=\"patch-skarner\">\n <a href=\"https://www.leagueoflegends.com/en-us/champions/skarner/\">\n  Skarner\n </a>\n</h3>\n",
            "<a href=\"https://www.leagueoflegends.com/en-us/champions/skarner/\">\n Skarner\n</a>\n",
            "<p class=\"summary\">\n Mana regen growth increased. Q damage decreased, buff no longer refreshed when hitting wards/plants. W slow decreased.\n</p>\n",
            "<blockquote class=\"blockquote context\">\n Skarner is currently very overpowered, especially in elite play, where he\u2019s making the Rift AND enemy\u2019s boots quake. His potent early game often ends games before other champions can reach their power spikes which is why we\u2019re going after his early game. We\u2019ll be doing this by taking down a mix of his early damage and his sticking power with his Q and W. The mana regen line is here to give him a bit of compensation in top lane, as he\u2019s currently a much stronger jungler than top laner and players are clearly happy to play him in both roles.\n</blockquote>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title\">\n Base Stats\n</h4>\n",
            "<ul>\n <li>\n  <strong>\n   Mana Regeneration Growth\n  </strong>\n  : 0.6 \u21d2 0.75\n </li>\n</ul>\n",
            "<li>\n <strong>\n  Mana Regeneration Growth\n </strong>\n : 0.6 \u21d2 0.75\n</li>\n",
            "<strong>\n Mana Regeneration Growth\n</strong>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerQ.png\"/>\n Q - Shattered Earth / Upheaval\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerQ.png\"/>\n",
            "<ul>\n <li>\n  <strong>\n   Damage per Hit\n  </strong>\n  : 10/25/40/55/70 (+60% bonus AD) (+5% of his bonus health) \u21d2\n  <strong>\n   10/20/30/40/50\n  </strong>\n  (+60% bonus AD) (+5% of his bonus health)\n </li>\n <li>\n  <span class=\"removed\">\n   removed\n  </span>\n  Q no longer refreshes the buff duration upon attacking Wards or Plants.\n </li>\n</ul>\n",
            "<li>\n <strong>\n  Damage per Hit\n </strong>\n : 10/25/40/55/70 (+60% bonus AD) (+5% of his bonus health) \u21d2\n <strong>\n  10/20/30/40/50\n </strong>\n (+60% bonus AD) (+5% of his bonus health)\n</li>\n",
            "<strong>\n Damage per Hit\n</strong>\n",
            "<strong>\n 10/20/30/40/50\n</strong>\n",
            "<li>\n <span class=\"removed\">\n  removed\n </span>\n Q no longer refreshes the buff duration upon attacking Wards or Plants.\n</li>\n",
            "<span class=\"removed\">\n removed\n</span>\n",
            "<hr class=\"divider\"/>\n",
            "<h4 class=\"change-detail-title ability-title\">\n <img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerW.png\"/>\n W - Seismic Bastion\n</h4>\n",
            "<img src=\"https://am-a.akamaihd.net/image?f=https://ddragon.leagueoflegends.com/cdn/14.8.1/img/spell/SkarnerW.png\"/>\n",
            "<ul>\n <li>\n  <strong>\n   Slow\n  </strong>\n  : 20/25/30/35/40% \u21d2 20% at all ranks\n </li>\n <li>\n  <strong>\n   Shield\n  </strong>\n  : 9% maximum health \u21d2 8% maximum health\n </li>\n</ul>\n",
            "<li>\n <strong>\n  Slow\n </strong>\n : 20/25/30/35/40% \u21d2 20% at all ranks\n</li>\n",
            "<strong>\n Slow\n</strong>\n",
            "<li>\n <strong>\n  Shield\n </strong>\n : 9% maximum health \u21d2 8% maximum health\n</li>\n",
            "<strong>\n Shield\n</strong>\n",
            "<header class=\"header-primary\">\n <h2 id=\"patch-champion-radii-radiuses\">\n  Champion Radii (Radiuses?)\n </h2>\n</header>\n"
"""

# Parse the HTML with BeautifulSoup
soup = BeautifulSoup(html_content, 'html.parser')

# Define a simple HTML structure for displaying the patch notes
html_output = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Patch Notes Analysis</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .patch-note { background-color: #f4f4f4; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .patch-note h3 { color: #333; }
        .summary, blockquote { color: #666; }
        img { width: 100px; }
    </style>
</head>
<body>
    <h1>League of Legends Patch Notes Analysis</h1>
'''

# Iterate through each champion change block
for block in soup.select('.patch-change-block'):
    champion_name = block.find('h3').text.strip()
    champion_link = block.find('a')['href']
    champion_image = block.find('img')['src']
    summary = block.find('p', class_='summary').text.strip()
    context = block.find('blockquote', class_='blockquote').text.strip()

    # Append the champion block to the HTML output
    html_output += f'''
    <div class="patch-note">
        <h2>Changes for {champion_name}</h2>
        <a href="{champion_link}">
            <img src="{champion_image}" alt="{champion_name}">
        </a>
        <h3>Summary of Changes</h3>
        <p>{summary}</p>
        <h3>Developer Commentary</h3>
        <blockquote>{context}</blockquote>
    </div>
    '''

# Close the HTML tags
html_output += '''
</body>
</html>
'''

# Output the HTML to a file
with open('patch_notes.html', 'w', encoding='utf-8') as file:
    file.write(html_output)

print("HTML file has been created!")